import json

nb = json.load(open(r'd:\Tseng\game_eeg\RF_PLV\rf_plv_be_combined.ipynb', encoding='utf-8'))

def make_cell(src, cid):
    return {
        'cell_type': 'code',
        'execution_count': None,
        'id': cid,
        'metadata': {},
        'outputs': [],
        'source': src
    }

# ── Cell 10: 收集決策路徑 ──
src10 = [
    "# ══════════════════════════════════════════════════════════════════\n",
    "# 決策路徑分析 — Parietal\n",
    "# 對每個 subject LOSO 重新訓練 RF，用 decision_path() 收集\n",
    "# 每個 session 在每棵樹走過幾個節點、預測信心值等資訊\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "\n",
    "import pandas as pd\n",
    "\n",
    "ch_idx   = REGIONS['Parietal']\n",
    "feat_plv = extract_plv_features(X_plv, ch_idx)\n",
    "feat_be  = extract_be_features(X_be,  ch_idx)\n",
    "\n",
    "path_records = []\n",
    "\n",
    "for test_subject in subject_ids:\n",
    "    test_mask  = subject_split == test_subject\n",
    "    train_mask = ~test_mask\n",
    "    y_tr = y_all[train_mask].astype(int)\n",
    "    y_te = y_all[test_mask].astype(int)\n",
    "\n",
    "    sc_p  = StandardScaler()\n",
    "    plv_tr = sc_p.fit_transform(feat_plv[train_mask])\n",
    "    plv_te = sc_p.transform(feat_plv[test_mask])\n",
    "    pca_p = PCA(n_components=0.95)\n",
    "    plv_tr = pca_p.fit_transform(plv_tr)\n",
    "    plv_te = pca_p.transform(plv_te)\n",
    "\n",
    "    sc_b  = StandardScaler()\n",
    "    be_tr  = sc_b.fit_transform(feat_be[train_mask])\n",
    "    be_te  = sc_b.transform(feat_be[test_mask])\n",
    "    pca_b = PCA(n_components=0.95)\n",
    "    be_tr  = pca_b.fit_transform(be_tr)\n",
    "    be_te  = pca_b.transform(be_te)\n",
    "\n",
    "    X_tr = np.hstack([plv_tr, be_tr])\n",
    "    X_te = np.hstack([plv_te, be_te])\n",
    "\n",
    "    clf = RandomForestClassifier(n_estimators=500, class_weight='balanced',\n",
    "                                  random_state=42, n_jobs=-1)\n",
    "    clf.fit(X_tr, y_tr)\n",
    "\n",
    "    for ses_idx, (x_row, y_row) in enumerate(zip(X_te, y_te)):\n",
    "        x_2d  = x_row.reshape(1, -1)\n",
    "        pred  = clf.predict(x_2d)[0]\n",
    "        proba = clf.predict_proba(x_2d)[0]\n",
    "        node_counts = [clf.estimators_[k].decision_path(x_2d).nnz\n",
    "                       for k in range(len(clf.estimators_))]\n",
    "        path_records.append({\n",
    "            'subject':    test_subject,\n",
    "            'true_label': CLASS_NAMES[y_row],\n",
    "            'pred_label': CLASS_NAMES[pred],\n",
    "            'correct':    pred == y_row,\n",
    "            'session':    f'ss0{ses_idx+1}',\n",
    "            'prob_am':    proba[0],\n",
    "            'prob_ma':    proba[1],\n",
    "            'prob_pr':    proba[2],\n",
    "            'conf':       float(proba[pred]),\n",
    "            'mean_nodes': float(np.mean(node_counts)),\n",
    "            'std_nodes':  float(np.std(node_counts)),\n",
    "        })\n",
    "\n",
    "df_path = pd.DataFrame(path_records)\n",
    "print(f'共 {len(df_path)} 筆 session 路徑記錄（{len(subject_ids)} subjects × 3 sessions）')\n",
    "df_path.head(6)"
]

# ── Cell 11: 摘要表 ──
src11 = [
    "# ── 每個 Subject 的決策路徑摘要表 ──\n",
    "# true class / 3 session 預測結果 & 信心值 / 平均路徑節點數\n",
    "\n",
    "print('=' * 115)\n",
    "print('Parietal — RF Decision Path Summary  (每棵樹平均走過節點數 = 路徑長度)')\n",
    "print('=' * 115)\n",
    "print(f'{\"Subject\":<15s} {\"True\":>8s} '\n",
    "      f'{\"ss01 pred(conf)\":>16s} {\"ss02 pred(conf)\":>16s} {\"ss03 pred(conf)\":>16s} '\n",
    "      f'{\"Avg Nodes\":>10s} {\"OK/3\":>5s}')\n",
    "print('-' * 115)\n",
    "\n",
    "for sub_id in subject_ids:\n",
    "    rows = df_path[df_path['subject'] == sub_id].sort_values('session')\n",
    "    true_lbl  = rows.iloc[0]['true_label']\n",
    "    ses_strs  = []\n",
    "    n_correct = 0\n",
    "    all_nodes = []\n",
    "    for _, row in rows.iterrows():\n",
    "        marker = 'O' if row['correct'] else 'X'\n",
    "        ses_strs.append(f\"{row['pred_label'][:4]}({row['conf']:.2f}){marker}\")\n",
    "        n_correct += int(row['correct'])\n",
    "        all_nodes.append(row['mean_nodes'])\n",
    "    avg_nodes = np.mean(all_nodes)\n",
    "    print(f'{sub_id:<15s} {true_lbl:>8s} '\n",
    "          f'{ses_strs[0]:>16s} {ses_strs[1]:>16s} {ses_strs[2]:>16s} '\n",
    "          f'{avg_nodes:10.1f} {n_correct:>4d}/3')\n",
    "\n",
    "print('=' * 115)\n",
    "print(f'\\n整體 session Acc = {df_path[\"correct\"].mean():.3f}  '\n",
    "      f'正確={df_path[\"correct\"].sum()}/{len(df_path)}')\n",
    "print(f'平均路徑長度 = {df_path[\"mean_nodes\"].mean():.1f} 節點/樹  '\n",
    "      f'(正確: {df_path[df_path[\"correct\"]][\"mean_nodes\"].mean():.1f}  '\n",
    "      f'錯誤: {df_path[~df_path[\"correct\"]][\"mean_nodes\"].mean():.1f})')\n"
]

# ── Cell 12: 路徑長度 + 信心值圖 ──
src12 = [
    "# ── 路徑長度分佈 + 信心值分析 ──\n",
    "\n",
    "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
    "\n",
    "# 1) 各 class 路徑長度 violin\n",
    "ax = axes[0]\n",
    "groups = [df_path[df_path['true_label'] == c]['mean_nodes'].values for c in CLASS_NAMES]\n",
    "vp = ax.violinplot(groups, positions=[0,1,2], showmedians=True)\n",
    "for body in vp['bodies']:\n",
    "    body.set_alpha(0.6)\n",
    "ax.set_xticks([0,1,2])\n",
    "ax.set_xticklabels(CLASS_NAMES)\n",
    "ax.set_ylabel('Mean nodes per tree')\n",
    "ax.set_title('Decision Path Length by Class\\n(Parietal, LOSO)')\n",
    "ax.grid(axis='y', alpha=0.3)\n",
    "\n",
    "# 2) 正確 vs 錯誤 路徑長度\n",
    "ax = axes[1]\n",
    "ax.hist(df_path[df_path['correct']]['mean_nodes'],  bins=20, alpha=0.6,\n",
    "        color='steelblue', label=f'Correct (n={df_path[\"correct\"].sum()})')\n",
    "ax.hist(df_path[~df_path['correct']]['mean_nodes'], bins=20, alpha=0.6,\n",
    "        color='tomato',    label=f'Wrong   (n={(~df_path[\"correct\"]).sum()})')\n",
    "ax.set_xlabel('Mean nodes per tree')\n",
    "ax.set_ylabel('Count')\n",
    "ax.set_title('Path Length: Correct vs Wrong')\n",
    "ax.legend(); ax.grid(alpha=0.3)\n",
    "\n",
    "# 3) per-subject 平均信心值\n",
    "ax = axes[2]\n",
    "sub_conf = df_path.groupby('subject')['conf'].mean().reset_index()\n",
    "sub_conf['true_label'] = sub_conf['subject'].map(lambda s: CLASS_NAMES[subject_labels[s]])\n",
    "sub_conf = sub_conf.sort_values(['true_label','conf'], ascending=[True, False])\n",
    "color_map = {'amateur': '#4C72B0', 'master': '#DD8452', 'prof': '#55A868'}\n",
    "bar_colors = [color_map[lbl] for lbl in sub_conf['true_label']]\n",
    "ax.barh(range(len(sub_conf)), sub_conf['conf'], color=bar_colors, alpha=0.8)\n",
    "ax.set_yticks(range(len(sub_conf)))\n",
    "ax.set_yticklabels(sub_conf['subject'], fontsize=7)\n",
    "ax.set_xlabel('Mean confidence (3-session avg)')\n",
    "ax.set_title('Per-Subject Mean Confidence')\n",
    "ax.axvline(x=0.5, color='gray', linestyle='--', alpha=0.6)\n",
    "from matplotlib.patches import Patch\n",
    "ax.legend(handles=[Patch(color=v, label=k) for k,v in color_map.items()], fontsize=8)\n",
    "ax.grid(axis='x', alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(r'D:\\Tseng\\game_eeg\\RF_PLV\\rf_path_confidence.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "high_wrong = df_path[(df_path['conf'] > 0.6) & ~df_path['correct']]\n",
    "print(f'高信心(>0.6)但分類錯誤: {len(high_wrong)} sessions')\n",
    "if len(high_wrong):\n",
    "    print(high_wrong[['subject','true_label','pred_label','conf','session']].to_string(index=False))\n"
]

# ── Cell 13: Feature Importance ──
src13 = [
    "# ── Feature Importance（原始 PLV / BE 特徵空間）──\n",
    "# RF importance 定義在 PCA 空間；投影回原始空間以便解讀\n",
    "\n",
    "ch_idx = REGIONS['Parietal']\n",
    "fp_raw = extract_plv_features(X_plv, ch_idx)\n",
    "fb_raw = extract_be_features(X_be, ch_idx)\n",
    "sc_p2 = StandardScaler(); fp_raw = sc_p2.fit_transform(fp_raw)\n",
    "pca_p2 = PCA(n_components=0.95); fp_raw = pca_p2.fit_transform(fp_raw)\n",
    "sc_b2 = StandardScaler(); fb_raw = sc_b2.fit_transform(fb_raw)\n",
    "pca_b2 = PCA(n_components=0.95); fb_raw = pca_b2.fit_transform(fb_raw)\n",
    "X_full2 = np.hstack([fp_raw, fb_raw])\n",
    "\n",
    "rf_full2 = RandomForestClassifier(n_estimators=500, class_weight='balanced',\n",
    "                                   random_state=42, n_jobs=-1)\n",
    "rf_full2.fit(X_full2, y_all.astype(int))\n",
    "\n",
    "n_plv_pcs2 = fp_raw.shape[1]\n",
    "n_be_pcs2  = fb_raw.shape[1]\n",
    "imp = rf_full2.feature_importances_\n",
    "\n",
    "imp_plv_orig = np.abs(pca_p2.components_).T @ imp[:n_plv_pcs2]\n",
    "imp_be_orig  = np.abs(pca_b2.components_).T @ imp[n_plv_pcs2:]\n",
    "\n",
    "ch_names_pari = [CH_NAMES[i] for i in REGIONS['Parietal']]\n",
    "n_ch = len(ch_names_pari)\n",
    "pairs = [(ch_names_pari[i], ch_names_pari[j])\n",
    "         for i in range(n_ch) for j in range(i+1, n_ch)]\n",
    "plv_feat_names = [f'{a}-{b}_{bnd}' for bnd in BAND_NAMES for a, b in pairs]\n",
    "be_feat_names  = [f'{ch}_{b}' for ch in ch_names_pari for b in BAND_NAMES]\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n",
    "\n",
    "ax = axes[0]\n",
    "top20 = np.argsort(imp_plv_orig)[::-1][:20]\n",
    "ax.barh(range(20), imp_plv_orig[top20][::-1], color='#4C72B0', alpha=0.8)\n",
    "ax.set_yticks(range(20))\n",
    "ax.set_yticklabels([plv_feat_names[i] for i in top20[::-1]], fontsize=8)\n",
    "ax.set_xlabel('Importance (projected from PCA)')\n",
    "ax.set_title('Top-20 PLV Features (Parietal)')\n",
    "ax.grid(axis='x', alpha=0.3)\n",
    "\n",
    "ax = axes[1]\n",
    "top_be = np.argsort(imp_be_orig)[::-1][:20]\n",
    "ax.barh(range(len(top_be)), imp_be_orig[top_be][::-1], color='#DD8452', alpha=0.8)\n",
    "ax.set_yticks(range(len(top_be)))\n",
    "ax.set_yticklabels([be_feat_names[i] for i in top_be[::-1]], fontsize=8)\n",
    "ax.set_xlabel('Importance (projected from PCA)')\n",
    "ax.set_title('Top-20 BE Features (Parietal)')\n",
    "ax.grid(axis='x', alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(r'D:\\Tseng\\game_eeg\\RF_PLV\\rf_feature_importance.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "print(f'PLV branch importance 總和 = {imp[:n_plv_pcs2].sum():.3f}')\n",
    "print(f'BE  branch importance 總和 = {imp[n_plv_pcs2:].sum():.3f}')\n"
]

# ── Cell 14: 單棵樹視覺化 ──
src14 = [
    "# ── 單棵決策樹視覺化（max_depth=4，方便閱讀）──\n",
    "from sklearn.tree import plot_tree\n",
    "\n",
    "feat_names2 = ([f'PLV_PC{i+1}' for i in range(n_plv_pcs2)] +\n",
    "               [f'BE_PC{i+1}'  for i in range(n_be_pcs2)])\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(22, 8))\n",
    "plot_tree(\n",
    "    rf_full2.estimators_[0],\n",
    "    max_depth=4,\n",
    "    feature_names=feat_names2,\n",
    "    class_names=CLASS_NAMES,\n",
    "    filled=True,\n",
    "    rounded=True,\n",
    "    fontsize=8,\n",
    "    ax=ax\n",
    ")\n",
    "ax.set_title('RF Tree #0 (Parietal, PLV+BE PCA features, max_depth=4 shown)', fontsize=11)\n",
    "plt.tight_layout()\n",
    "plt.savefig(r'D:\\Tseng\\game_eeg\\RF_PLV\\rf_single_tree.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(f'樹的實際深度: {rf_full2.estimators_[0].get_depth()}  (圖只顯示前 4 層)')\n"
]

nb['cells'].extend([
    make_cell(src10, 'cell-10'),
    make_cell(src11, 'cell-11'),
    make_cell(src12, 'cell-12'),
    make_cell(src13, 'cell-13'),
    make_cell(src14, 'cell-14'),
])

with open(r'd:\Tseng\game_eeg\RF_PLV\rf_plv_be_combined.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print('Done, total cells:', len(nb['cells']))
